# Generated by Django 4.1.8 on 2023-04-27 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_header'),
    ]

    operations = [
        migrations.RenameField(
            model_name='header',
            old_name='title',
            new_name='text',
        ),
    ]
