# Generated by Django 4.1.8 on 2023-04-27 20:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_rename_title_header_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='header',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='home.header'),
        ),
    ]
