# Generated by Django 4.1.8 on 2023-04-28 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_pageheadersorderable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='header',
        ),
    ]
