# Generated by Django 4.1.8 on 2023-04-28 23:59

from django.db import migrations
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_pageheadersphotoorderable'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='hero',
            field=wagtail.fields.StreamField([('image', wagtail.images.blocks.ImageChooserBlock())], null=True, use_json_field=True),
        ),
    ]
