# Generated by Django 4.1.8 on 2023-04-29 00:23

from django.db import migrations
import django.utils.timezone
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_homepage_hero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='hero',
            field=wagtail.fields.StreamField([('image', wagtail.images.blocks.ImageChooserBlock()), ('message', wagtail.blocks.CharBlock(form_classname='title'))], default=django.utils.timezone.now, use_json_field=True),
            preserve_default=False,
        ),
    ]
