# Generated by Django 4.1.8 on 2023-05-15 00:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_remove_blogpagegalleryimage_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pageheadersphotoorderable',
            name='header_photo',
        ),
        migrations.RemoveField(
            model_name='pageheadersphotoorderable',
            name='page',
        ),
        migrations.AddField(
            model_name='homepage',
            name='header',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='home.header'),
        ),
        migrations.DeleteModel(
            name='PageHeadersOrderable',
        ),
        migrations.DeleteModel(
            name='PageHeadersPhotoOrderable',
        ),
    ]
