# Generated by Django 4.1.8 on 2023-05-16 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_remove_pageheadersphotoorderable_header_photo_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homepage',
            old_name='header',
            new_name='home_header',
        ),
    ]
