# Generated by Django 4.1.8 on 2023-06-26 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_gallery'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gallery',
            options={'verbose_name': 'Gallery Image'},
        ),
    ]
