# Generated by Django 4.1.8 on 2023-09-17 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0027_gallery_background_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallery',
            name='background_image',
        ),
    ]
