# Generated by Django 4.1.8 on 2023-09-18 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0031_customimage_alter_gallery_caption_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customimage',
            name='caption',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
