# Generated by Django 4.1.8 on 2023-09-18 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0032_customimage_caption'),
    ]

    operations = [
        migrations.AddField(
            model_name='customimage',
            name='camera',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
