# Generated by Django 4.1.8 on 2023-09-19 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0035_alter_gallery_images_alter_header_logo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customimage',
            name='copyright',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
