# Generated by Django 4.1.8 on 2023-09-19 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0036_customimage_copyright'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customimage',
            name='caption',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
