# Generated by Django 4.1.8 on 2023-10-12 08:42

from django.db import migrations, models
import django.db.models.deletion
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0083_workflowcontenttype'),
        ('home', '0038_customimage_shutter'),
    ]

    operations = [
        migrations.CreateModel(
            name='Terms',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('text', wagtail.fields.RichTextField(blank=True, null=True)),
                ('created', models.DateField(blank=True, null=True, verbose_name='Date')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
