# Generated by Django 4.1.8 on 2023-11-14 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0041_homepage_hero'),
    ]

    operations = [
        migrations.AddField(
            model_name='customimage',
            name='aperture',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
