# Generated by Django 4.1.8 on 2023-05-08 19:34

from django.db import migrations
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_blogdetailpage_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogdetailpage',
            name='content',
            field=wagtail.fields.StreamField([('title_and_text', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(help_text='Add your title', required=True)), ('text', wagtail.blocks.TextBlock(help_text='Add additional text', required=False))])), ('image', wagtail.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock()), ('text', wagtail.blocks.TextBlock(max_length=200, required=True))])), ('text_body', wagtail.blocks.StructBlock([('text', wagtail.blocks.TextBlock(max_length=2000, required=True)), ('detailed_text', wagtail.blocks.RichTextBlock(max_length=2000, required=False))])), ('gallery', wagtail.blocks.ListBlock(wagtail.images.blocks.ImageChooserBlock()))], use_json_field=True),
        ),
    ]
