# Generated by Django 4.1.8 on 2023-05-26 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_blogauthorsorderable'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogauthor',
            name='bio',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
