# Generated by Django 4.1.8 on 2023-07-28 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_alter_blogdetailpage_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogdetailpage',
            name='summary',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
