# Generated by Django 4.1.8 on 2023-08-18 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_blogdetailpage_summary'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorSocials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('name', models.CharField(max_length=255)),
                ('url', models.URLField()),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author_socials', to='blog.blogauthor')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
