# Generated by Django 4.1.8 on 2023-08-18 11:51

from django.db import migrations
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_authorsocials'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authorsocials',
            name='name',
        ),
        migrations.AlterField(
            model_name='authorsocials',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='author_socials', to='blog.blogauthor'),
        ),
    ]
