# Generated by Django 4.1.8 on 2023-08-18 11:54

from django.db import migrations
import django.utils.timezone
import wagtail_icon_picker.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0021_remove_authorsocials_name_alter_authorsocials_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='authorsocials',
            name='icon',
            field=wagtail_icon_picker.fields.IconField(default=django.utils.timezone.now, max_length=70),
            preserve_default=False,
        ),
    ]
