# Generated by Django 4.1.8 on 2023-08-18 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0023_remove_authorsocials_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='authorsocials',
            name='network',
            field=models.CharField(choices=[('Facebook', 'Facebook'), ('Twitter', 'Twitter'), ('Github', 'Github')], default='Facebook', max_length=20),
        ),
    ]
