# Generated by Django 4.1.8 on 2023-09-24 23:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0038_customimage_shutter'),
        ('blog', '0024_authorsocials_network'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogauthor',
            name='image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='home.customimage'),
        ),
    ]
