# Generated by Django 4.1.8 on 2023-10-23 23:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0039_terms'),
        ('blog', '0026_alter_blogdetailpage_blog_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogcategories',
            name='icon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='home.customimage'),
        ),
    ]
