# Generated by Django 4.1.8 on 2023-10-25 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0028_alter_blogdetailpage_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogdetailpage',
            name='summary',
            field=models.CharField(blank=True, default='sumamry', max_length=100),
        ),
    ]
