# Generated by Django 4.1.8 on 2023-11-15 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0030_alter_blogauthor_facebook_alter_blogauthor_instagram_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogdetailpage',
            name='custom_title',
        ),
        migrations.AlterField(
            model_name='blogdetailpage',
            name='summary',
            field=models.CharField(blank=True, default='sumamry', help_text='This appears under the blog on recent posts', max_length=100),
        ),
    ]
