# Generated by Django 4.2.8 on 2023-12-22 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0044_formpage_alter_customrendition_file_formfield'),
        ('blog', '0037_blogdetailpage_title_background_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogdetailpage',
            name='title_background',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='home.customimage'),
        ),
    ]
