# Generated by Django 4.2.8 on 2023-12-22 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0044_formpage_alter_customrendition_file_formfield'),
        ('blog', '0038_alter_blogdetailpage_title_background'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogdetailpage',
            name='blog_image',
            field=models.ForeignKey(help_text="This is the main blog image appearing at the top of the post \n        and it's 'thumbnail; across the site", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='home.customimage'),
        ),
        migrations.AlterField(
            model_name='blogdetailpage',
            name='summary',
            field=models.CharField(blank=True, default='sumamry', help_text='This appears under the blog on \n                               recent posts section of the Homepage', max_length=100),
        ),
    ]
