# Generated by Django 4.2.8 on 2023-12-25 12:45

from django.db import migrations
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0040_blogtype'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogdetailpage',
            name='type',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, to='blog.blogtype'),
        ),
    ]
