# Generated by Django 4.2.8 on 2023-12-25 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0041_blogdetailpage_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogdetailpage',
            name='background',
            field=models.BooleanField(default=True),
        ),
    ]
