# Generated by Django 4.2.8 on 2024-01-21 21:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0045_homepage_search_image'),
        ('blog', '0043_alter_blogdetailpage_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogdetailpage',
            name='search_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='home.customimage', verbose_name='Search image'),
        ),
        migrations.AddField(
            model_name='bloglistingpage',
            name='search_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='home.customimage', verbose_name='Search image'),
        ),
    ]
