# Generated by Django 4.1.8 on 2023-10-10 11:55

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('sitesettings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='privacy_notice',
            name='notice',
            field=wagtail.fields.RichTextField(default='privacy'),
        ),
    ]
