# Generated by Django 4.1.8 on 2023-10-10 12:04

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('sitesettings', '0003_copyright_notice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='copyright_notice',
            name='copyright_info',
            field=wagtail.fields.RichTextField(default='copyright'),
        ),
    ]
