# Generated by Django 4.1.8 on 2023-10-11 11:47

from django.db import migrations, models
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('sitesettings', '0005_footersettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='FooterNotices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('text', wagtail.fields.RichTextField()),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='footersettings',
            name='Copyright',
        ),
        migrations.RemoveField(
            model_name='footersettings',
            name='Privacy',
        ),
        migrations.AddField(
            model_name='footersettings',
            name='footer_messages',
            field=models.BooleanField(default=True, help_text='Untick to hide', verbose_name='Add modal popups to footer?'),
        ),
    ]
