# Generated by Django 4.1.8 on 2023-10-11 12:00

from django.db import migrations
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('sitesettings', '0006_footernotices_remove_footersettings_copyright_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='footernotices',
            name='settings_page',
            field=modelcluster.fields.ParentalKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notices', to='sitesettings.footersettings'),
        ),
    ]
