# Generated by Django 4.1.8 on 2023-11-12 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0083_workflowcontenttype'),
        ('sitesettings', '0009_caontactinfo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CaontactInfo',
            new_name='ContactInfo',
        ),
    ]
